modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL=""
displayURL=""
logoFile="logo.png"
#credits="SilentChaos for his lib and mod silentgear"
authors="dragoni7"

[[mods]]
    modId="silentcompat"
    version="${file.jarVersion}"
    displayName="Silent Compat"
    description='''
    wip
    '''

[[dependencies.silentcompat]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="silentlib"
    mandatory=true
    versionRange="[7.0.1,)"
    ordering="NONE"
    side="BOTH"