modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL=""
logoFile="logo.png"
#credits="SilentChaos for his lib and mod silentgear. To the Silent's Mods discord for material references / ideas"
authors="dragoni7"

[[mods]]
    modId="silentcompat"
    version="${file.jarVersion}"
    displayName="Silent Compat"
    description='''
    wip
    '''

[[dependencies.silentcompat]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="silentgear"
    mandatory=true
    versionRange="[3.1.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="botania"
    mandatory=false
    versionRange="[1.19.2-440-FORGE,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="silentlib"
    mandatory=true
    versionRange="[7.0.3,)"
    ordering="NONE"
    side="BOTH"