modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL=""
logoFile="logo.png"
#credits="SilentChaos for his lib and mod silentgear"
authors="dragoni7"

[[mods]]
    modId="silentcompat"
    version="${file.jarVersion}"
    displayName="Silent Compat"
    description='''
    wip
    '''

[[dependencies.silentcompat]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="silentgear"
    mandatory=true
    versionRange="[3.0.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.dreamland]]
    modId="dreamland"
    mandatory=false
    versionRange="[1.2.0.4,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.alexsmobs]]
    modId="alexsmobs"
    mandatory=false
    versionRange="[1.20.2,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.silentcompat]]
    modId="silentlib"
    mandatory=true
    versionRange="[7.0.1,)"
    ordering="NONE"
    side="BOTH"